### ISSUE TITLE
Can't use the customize UI with v1.5

### ISSUE THREAD

**Issue by larserhardsen** [auth0/auth0-cli#1076] opened 2024-09-17 09:32 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After upgrading from v1.4 to v1.5 the command `auth0 ul customize` no longer provides access to edit the Universal Login of my tenant. Instead, it opens up on travel0.us.auth0.com and fails.

Downgrading to v1.4 restores the functionality.

### Expectation

I expected the same behaviour as in v1.4.

### Reproduction

It seems to be fairly consistent, as we have tried this on two different machines.

1. Install auth0-cli via `brew` on MacOS.
2. Authenticate via `auth0 login`
3. Attempt to edit a tenant via the `auth0 ul customize` command
4. The browser attempts to load the UI for the travel0.us.auth0.com tenant rather than my "own" tenant.

### Auth0 CLI version

1.5.0

**Comment by brth31** [comment] 2024-09-17 14:31
@larserhardsen the cli attempting to load `travel0.us.auth0.com` is just a temporary loading state. Could you confirm if you're still facing this issue?

**Comment by larserhardsen** [comment] 2024-09-18 08:44
Yes, I am unfortunately still facing the issue. It seems that the websocket connections hangs:
<img width="1338" alt="image" src="https://github.com/user-attachments/assets/c6a066ea-c27c-4a13-ba32-5dbad18da1cd">

**Comment by developerkunal** [comment] 2024-09-19 14:31
Hi @larserhardsen,

Sorry for the delay in responding!

Could you provide the steps to reproduce the issue? Additionally, can you confirm if you have a custom domain set up and if it's verified? Is the tool not loading at all, and what system and OS are you using?

Are you also trying to use prompt partials?

Thank you!

**Comment by tylerkeesling** [comment] 2024-09-19 18:35
@developerkunal Hey Kunal, this issue is related to the custom prompts for passwordless flows.

**Comment by larserhardsen** [comment] 2024-09-20 07:50
> Hi @larserhardsen,
> 
> Sorry for the delay in responding!
> 
> Could you provide the steps to reproduce the issue? Additionally, can you confirm if you have a custom domain set up and if it's verified? Is the tool not loading at all, and what system and OS are you using?
> 
> Are you also trying to use prompt partials?
> 
> Thank you!

Hi @developerkunal 

Today things actually look better, for some reason. When running `auth0 ul customize` there is a delay of approx 10 secs where the browser window shows the travel0.us.auth0.com in a loading state, and then my tenant loads, however with a lot of broken images.

We have not yet used the prompt partials, and we do have a custom domain set up. As stated previously, the setup works on version 1.4 of the CLI. I am using MacOS 14/15.

As far as reproducing, I have given the steps in the issue description. Things were working fine on version 1.4, then I upgraded to version 1.5 via Brew, and when trying to use the `auth0 ul customize` it's either not loading or loading very, very slowly.

**Comment by developerkunal** [comment] 2024-09-20 07:53
Hi @larserhardsen ,
Can you attach the screenshot of the broken images?

**Comment by developerkunal** [comment] 2024-09-20 07:56
Hi @tylerkeesling ,
Thank you! 

> {
  "statusCode": 403,
  "error": "Forbidden",
  "message": "Your account does not have custom prompts passwordless support enabled",
  "errorCode": "operation_not_supported"
}

I understand the issue you are facing, because login passwordless is still EA and not available for everyone it's throwing an error.

Let me take a look at when it will be available for everyone, else I will release a patch to fix the issue.

**Comment by larserhardsen** [comment] 2024-09-20 07:59
> Hi @larserhardsen , Can you attach the screenshot of the broken images?

I can see that the broken URL to the image is https://auth0.github.io/universal-login-prompts/static/img/logo-generic.svg

<img width="1355" alt="image" src="https://github.com/user-attachments/assets/b03b3065-99f7-409b-8235-cf8288a9c244">

**Comment by developerkunal** [comment] 2024-09-20 08:03
Can you also check in Version 1.4 is that image is loading?

**Comment by developerkunal** [comment] 2024-09-20 08:19
Hi @larserhardsen,

I've reviewed the issue regarding the image, but it doesn't seem to be causing any significant impact. I also checked, and this issue exists in version 1.4.0, so I don't believe it's contributing to the problem.

As for the loading speed, I suspect it's due to the additional requests we've introduced for loading partial prompts. When we start the `ul customize` command, it fetches all the data and stores it in the state. Since partials contain a large number of prompts, this may be contributing to the slowdown.

Let me investigate further, and I'll come up with a solution to address this.

**Comment by developerkunal** [comment] 2024-09-26 05:26
Hi @tylerkeesling ,
can you check now i think it is available for everyone. you should not get that error anymore!

**Comment by developerkunal** [comment] 2024-09-26 05:29
Hi @larserhardsen,

I've reviewed the situation and, for now, we are unable to optimize the speed of UL customization. Currently, it will largely depend on your internet connection. However, we are actively working on improving the performance. There will be significant changes ahead—not only to the CLI but also to the front end to better support UL customization.

**Comment by developerkunal** [comment] 2024-09-30 09:20
Hi @larserhardsen
Closing this issue for now. If needed, feel free to reopen it!

**Closed by developerkunal** 2024-09-30 09:20 UTC
Labels: bug
