### ISSUE TITLE
Error when trying to edit login-id prompt text

### ISSUE THREAD

**Issue by daschi** [auth0/auth0-cli#575] opened 2022-12-26 18:21 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello! I am using the auth0 cli to update the prompt texts for `login-id`, however when I run:

`auth0 branding texts update -l en login-id`

I see the following error message:

```
!!     Uh oh. Something went wrong.
!!     If this problem keeps happening feel free to report an issue at
!!
!!     https://github.com/auth0/auth0-cli/issues/new/choose
```

If I run `auth0 branding texts update -l en login`

I am able to change the text for the login prompts, however I am using the identifier first login page so I believe I need to edit `login-id` texts.

Thank you for your help and let me know if I can provide more info!

### Expectation

Expect `auth0 branding texts update -l en login-id` to open an editor to edit the prompt texts.

### Reproduction

1. Given I am logged into my auth0 tenant
2. When I run `auth0 branding texts update -l en login-id`
3. I see a generic error that something went wrong.

### Auth0 CLI version

auth0 version 0.13.1 42a703dd07e148a3a74be787180ac1e9938b63cd

**Comment by willvedd** [comment] 2023-01-05 22:17
@daschi – Thanks for submitting this issue, it certainly appears to be frustrating. I'm currently in the middle of troubleshooting this and have determined that it's a duplicate of #515. For that reason, I'm opting to close this ticket and communicate all status updates in the other ticket. Thank you for your patience!

**Closed by willvedd** 2023-01-05 22:17 UTC
Labels: bug
