### ISSUE TITLE
auth0 branding templates update throws panic

### ISSUE THREAD

**Issue by ChristopherGillis** [auth0/auth0-cli#638] opened 2023-02-03 00:01 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I installed on MacOs using brew, logged in, and ran `auth0 branding templates update` as per the instructions.

I received:
```
⣻panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1aa7d1e]

goroutine 66 [running]:
github.com/auth0/auth0-cli/internal/cli.(*cli).obtainCustomTemplateData.func3()
        /home/runner/work/auth0-cli/auth0-cli/internal/cli/branding.go:435 +0x21e
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

### Expectation

I expected the terminal editor to open a custom template as per https://auth0.github.io/auth0-cli/auth0_branding_templates.html

### Reproduction

Run `auth0 branding templates update`

### Auth0 CLI version

0.13.1

**Comment by willvedd** [comment] 2023-02-03 00:45
Thanks for submitting this issue! It is a duplicate of #515 however, so I'm going to close this one out. But note that this has been fixed with [v1.0.0-beta.1 ](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0-beta.1) if you're so inclined to give that a shot. Otherwise, GA of v1.0.0 is coming up soon!

**Closed by willvedd** 2023-02-03 00:45 UTC
Labels: bug

**Comment by jsw** [comment] 2023-02-03 23:42
Happy to report this elsewhere, but  I ran into the same issue, downloaded 1.0.0-beta.1, but when I run `./auth0 universal-login templates update` I get the editor in my console but no browser window as expected in these docs

https://auth0.com/docs/customize/universal-login-pages/universal-login-page-templates#using-the-auth0-cli

**Comment by ChristopherGillis** [comment] 2023-02-13 21:49
Can confirm, beta release solves bug, and I see editor but no browser (which is fine by me). Thanks.
