### ISSUE TITLE
Default branding text for signup-password fails with 400 error: Invalid key "editLinkScreenReadableText"

### ISSUE THREAD

**Issue by jketcham** [auth0/auth0-cli#382] opened 2022-01-11 19:01 UTC
### Description

If I run `auth0 branding texts update signup-password`, don't make any edits to the returned texts (keep the defaults), and save/quit the editor, the API returns a 400 error with:

```
 ▸    Unable to set custom text for prompt signup-password and language en: 400 Bad Request: Invalid key "editLinkScreenReadableText" in screen "signup-password".
```

If I just remove that `editLinkScreenReadableText` key from the returned texts and then save/quit the editor, the changes are successful. 

I'm guessing this is an error further up the chain from the cli here, but figured this was the most relevant place to make this issue, and help anyone that runs into the same thing.

### Environment

- **Version of this library used:** auth0 version 0.11.3 9daa0c20e749790319a2d2a9eb1f349844b51252
- **Other relevant versions (language, server software, OS, browser):** Installed with homebrew

**Comment by Widcket** [comment] 2022-01-19 19:29
Hi @jketcham, thanks for raising this, and apologies for the delay.
I just tried `auth0 branding texts update signup-password`, and was able to update with the key `editLinkScreenReadableText`:

<img width="874" alt="Screen Shot 2022-01-19 at 16 26 56" src="https://user-images.githubusercontent.com/5055789/150200629-642ee9ab-a882-4d4c-a8da-2e11bc96a60e.png">

**Comment by Widcket** [comment] 2022-01-19 19:31
@sergiughf could you please take a look?

**Comment by jketcham** [comment] 2022-01-19 20:33
Huh interesting, here are some screenshots for how it's failing for me (just tried again, with 0.11.3):

<img width="842" alt="Screen Shot 2022-01-19 at 1 29 01 PM" src="https://user-images.githubusercontent.com/1548556/150208966-03641deb-cd96-4a5e-afc0-366c0a581677.png">
<img width="840" alt="Screen Shot 2022-01-19 at 1 28 50 PM" src="https://user-images.githubusercontent.com/1548556/150208968-ea4b0447-51a7-4a0f-84aa-ebec66b5ea11.png">

**Comment by sergiughf** [comment] 2022-01-20 14:36
I tried to reproduce as well but it is not failing for me either. I get exactly the same output as @Widcket

**Comment by jketcham** [comment] 2022-01-20 17:12
I wonder if there could be a difference since I installed the cli with homebrew? Or that my auth0 tenant is on `us.auth0.com` instead of just `auth0.com`?

**Comment by Widcket** [comment] 2022-01-21 02:02
@jketcham there should be no difference due the way you installed the CLI, or the region of your tenant. It's most likely due to tenant configuration.

**Comment by Widcket** [comment] 2022-01-25 01:40
@jketcham given that we cannot reproduce the issue in our tenants, and that you can work around it by removing the key from the template values, I'll go ahead and close the issue. Please let me know if you'd like to reopen, or if you have any further questions.

**Closed by Widcket** 2022-01-25 01:40 UTC
Labels: needs investigation
