### ISSUE TITLE
branding - update does not update template

### ISSUE THREAD

**Issue by BartJanvanAssen** [auth0/auth0-cli#383] opened 2022-01-14 09:06 UTC
### Description

Trying to update the login page using the CLI command:
![image](https://user-images.githubusercontent.com/4742816/149488201-a6d45034-b6dd-478f-82e1-cbfd38cbedca.png)
end up not uploading the new template.

### Reproduction

> see image 

### Environment

- CLI -v => auth0 version 0.11.3 9daa0c20e749790319a2d2a9eb1f349844b51252
- MacOS everything  (xCode, macos etc) updated to use this cli - yesterday.
- used VIM (default editor in iterm) to change the template "basic". added little JS

template i like to upload is basic with a little script tag:
```
<script>
var c = document.createElement('div');
const text = `By continuing you agree to our <a
              href="{DOMAIN}/EULA.pdf"
            >
              Terms of Service
            </a>

            and acknowledge the

            <a href="{DOMAIN}/privacy-notice.pdf">
              Privacy Policy
            </a>
`
c.innerHTML = text
c.style.paddingTop = '10px'
if(document.body.innerText.includes('Sign up')){
document.getElementsByTagName('form')[0].after(c)
}
</script>

```

Update: Also tried to add just a text so without the script tags and it also does not upload.

**Comment by Widcket** [comment] 2022-01-19 19:42
Hi @BartJanvanAssen, thanks for raising this.
I just tried editing a template, and was unable to reproduce the issue; the saved text showed up when running `auth0 branding templates show`:

<img width="714" alt="Screen Shot 2022-01-19 at 16 39 42" src="https://user-images.githubusercontent.com/5055789/150202315-c178e704-1fc3-4224-9cfd-03ca94b96556.png">

**Comment by BartJanvanAssen** [comment] 2022-01-19 19:48
With show it shows up correctly. Had to somehow activate it. In meanwhile i've clickd a few swit hes in the UI and then it was fixed ( could preroduce it in another tenant.)

Steps:
- branding -> universal login
- switch to classic - save - switch to new - save
- got login
- select custom template switch - notice custom page - select custom login page top of code box in login tab, select and deselect. 
- uncheck custom login page
- (not essential) push a new version via cli of cli template. 
- now the cli template works. 

Seen this for 2 tenants..
So somehow in the steps above ive set some boolean in auth0 backend i guess 😜

**Comment by Widcket** [comment] 2022-01-21 02:08
@BartJanvanAssen thanks for providing the reproduction steps. Unfortunately, that would be outside of the scope of the CLI (which is just a [Management API](https://auth0.com/docs/api/management/v2) client).
I'll close this issue for now, as it is not actionable by us. Please let me know if you'd prefer to reopen.

**Closed by Widcket** 2022-01-21 02:08 UTC
Labels: needs investigation
