### ISSUE TITLE
unable to login to a different tenant

### ISSUE THREAD

**Issue by bwoznicki** [auth0/auth0-cli#1003] opened 2024-05-29 09:11 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Unable to login "As a user" to a different tennant. Same as here [auth0 comunity issue](https://community.auth0.com/t/auth0-cli-unable-to-login-with-different-tenant/135110). But I am not sure if that is the CLI issue or the endpoint, in documentation there is a mention of some dropdown to choose tenant but I am not seeing this dropdown anywhere. Tested on linux/mac firefox/chrome/safari

### Expectation

`auth login` "As a user" should prompt for tenant

### Reproduction

I have several tenants in eu and us regions, but `auth login` always loggs in to the same tenant, which is not even my default tenant according to auth0 dashboard

### Auth0 CLI version

auth0 version 1.4.0 54e9a30eeb58a4a7e40e04dc19af6869036bfb32

**Comment by bwoznicki** [comment] 2024-05-29 09:22
Found the issue, its the prebuild binary, something is missing there. If I clone this repo and run directly with `go run . login` I now get the dropdown after confirming the code in the browser.

**Comment by developerkunal** [comment] 2024-06-18 09:39
Hi @bwoznicki,

I hope you are doing well. Sorry for the late response.

Are you still facing the issue? It might be due to cached data in your browser, as we haven't seen anyone else with the same problem, and I couldn't reproduce it. If the issue still exists, could you please provide the steps to reproduce it so I can investigate further?

Thank you! If the issue is resolved, we can close it.

**Closed** 2024-06-28 04:21 UTC
Labels: bug
